export const analysisJsonSchema = {
  name: 'dream_analysis',
  strict: true,
  schema: {
    type: 'object',
    additionalProperties: false,
    properties: {
      primaryLens: { type: 'string' },
      secondaryLens: { type: 'string' },
      confidence: { type: 'string', enum: ['low', 'medium', 'high'] },
      routeReason: { type: 'string' },
      routeEvidence: {
        type: 'array',
        items: { type: 'string' },
      },
      headline: { type: 'string' },
      atmosphere: { type: 'string' },
      observations: {
        type: 'array',
        items: { type: 'string' },
      },
      hypotheses: {
        type: 'array',
        items: { type: 'string' },
      },
      disconfirmingCues: {
        type: 'array',
        items: { type: 'string' },
      },
      questionsToHold: {
        type: 'array',
        items: { type: 'string' },
      },
      microAction: { type: 'string' },
      signalToTrack: { type: 'string' },
      humilityNote: { type: 'string' },
    },
    required: [
      'primaryLens',
      'secondaryLens',
      'confidence',
      'routeReason',
      'routeEvidence',
      'headline',
      'atmosphere',
      'observations',
      'hypotheses',
      'disconfirmingCues',
      'questionsToHold',
      'microAction',
      'signalToTrack',
      'humilityNote',
    ],
  },
};
